version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: urlshortener-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: urlshortener-cache
    restart: always
    ports:
      - "6379:6379"

  # shortener:
  #   build: ..
  #   container_name: urlshortener-app
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: "postgres://user:password@urlshortener-db:5432/urlshortener?sslmode=disable"
  #     REDIS_ADDR: "urlshortener-cache:6379"
  #   volumes:
  #     - ../migrations:/app/migrations  # Mount migrations correctly

volumes:
  pgdata:
  